version: '2.1'

services:
  r1:
    build: .
    volumes:
      - ./volumes/quagga/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: ospf:AS101
    privileged: true
    ports:
      #admin
      - 10011:2601
      #ospf
      - 10012:2604
      #ospf ipv6
      - 10013:2606
    networks:
      oam:
        ipv4_address: 192.11.2.1
        ipv6_address: 2001:0002:0011::1
      nr7:
        ipv4_address: 192.11.7.1
        ipv6_address: 2001:0007:0011::1
      nr1:
        ipv4_address: 192.11.1.2
        ipv6_address: 2001:0001:0011::2
          
  r2:
    build: .
    volumes:
      - ./volumes/quagga/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/quagga/r2/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./volumes/quagga/r2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image:  ospf:AS101
    privileged: true
    ports:
      #admin
      - 10021:2601
      #ospf
      - 10022:2604
      #ospf ipv6
      - 10023:2606
    networks:
      oam:
        ipv4_address: 192.11.2.2
        ipv6_address: 2001:0002:0011::2
      nr5:
        ipv4_address: 192.11.5.2
        ipv6_address: 2001:0005:0011::1

networks:
  oam:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.11.2.0/24
        - subnet: 2001:0007:0011::/64
  nr1:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.11.1.0/24
        - subnet: 2001:0001:0011::/64
  nr2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.11.2.0/24
        - subnet: 2001:0002:0011::/64
  nr5:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.11.5.0/24
        - subnet: 2001:0005:0011::/64
  nr7:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.11.7.0/24
        - subnet: 2001:0007:0011::/64